version: "3.9"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.4.0
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    ports: ["8000:8000"]
    volumes: ["./.dynamodb:/home/dynamodblocal/data"]
    environment:
      - AWS_REGION=eu-north-1

  grobid:
    image: grobid/grobid:0.8.2.1-full
    restart: unless-stopped
    ports: ["8070:8070"]
    environment:
      GROBID_MAX_CONCURRENT: "1"
      JAVA_OPTS: "-Xms512m -Xmx2g -Djava.awt.headless=true"
      consolidate: "true"
    volumes:
      - ./grobid-home/config/grobid.yaml:/opt/grobid/grobid-home/config/grobid.yaml:ro
